service: som-qualtrics-survey-responses
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-west-2
  memorySize: 512
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-west-2:324125712306:secret:som/qualtrics/api_key-iVmbWI"

    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref": SOMQualtricsSurveyResponseBucket
            - "/*"
  environment:
    BUCKET: ${self:custom.outputBucket}
    QUALTRICS_API_TOKEN: ${self:custom.qualtricsApiToken.SOM_QUALTRICS_API_TOKEN}
    QUALTRICS_DATA_CENTER: "ucsf.co1"

custom:
  outputBucket: "som-qualtrics-survey-responses-${opt:stage, self:provider.stage}"
  qualtricsApiToken: ${ssm:/aws/reference/secretsmanager/som/qualtrics/api_key}
  isScheduleEnabled:
    prod: true
    dev: false

functions:
  storeSurveys:
    timeout: 900
    handler: handler.storeSurveys
    events:
      - schedule:
          rate: rate(30 minutes)
          enabled: ${self:custom.isScheduleEnabled.${self:provider.stage}}
    environment:
      SURVEY_IDS: >
        SV_bK7vU2Zk1WzBOBf,
        SV_d6UsHGihbYWM4sd,
        SV_0SQhsikeG2St445,
        SV_4UVvdY2oDgOm6Db,
        SV_2498foz7l1fSGlD,
        SV_0pvpV6isPLivSvz,
        SV_9AXy9LNoKeX8bzf,
        SV_ac0zqC6911Dlhnn,
        SV_0VwcaXHEvY4mXRP,
        SV_bJmcqD98FQ8ateJ,
        SV_6PV2C7YezYaJc5n,
        SV_eJONoZyl22RTQ7I,
        SV_d5SG31YfRtk7wqi,
        SV_eLt4b4VUVsOHo8K,
        SV_07YN5dueqP7G1jE,
        SV_4I2tFtjn2SKS4rs,
        SV_5nVznH4lNXdoupM,
        SV_baoeGgFjsrIh2QK,
        SV_dhbV5NjglUWfQJ8,
        SV_eURUM5rOXOes52m,
        SV_ai5KlA9xHzZyZaC,
        SV_ea1LuAiQO9iwP7E,
        SV_eRG1fTe6AWEYO8u,
        SV_3V1AYWZusjO9kTs,
        SV_bCOJjNnqjQR62QS,
        SV_0lbCcF603lhHpVI,
        SV_29xEnB8p18Hteiq,
        SV_0xsAFMABnHNZGPI,
        SV_3CcjgGjPqc0GX8G,
        SV_0ky2FAissYpmLJQ,
        SV_dmrRccvHw0XC0Ga,
        SV_9RlNfF3BcVT0h0y,
        SV_50BvQ1VUAaaTb5I,
        SV_eCMLUfqMD4QtP3o,
        SV_eWJkCCTNDFl6Utg,
        SV_cuoeJeUS887lh8W,
        SV_9HrXitTGaSZsbhc,
        SV_414lGArbaTrQ99z,
        SV_bPkLDafzevLpV8G,
        SV_eLGAunyqJVcZpga,
        SV_cLT4SpYbPaOxXSK,
        SV_efgIdP3HKV02fSC,
        SV_3w960IpsKnyulFQ,
        SV_55Dd6ZiyYIX1Jqu,
        SV_bwq5WnHid7GzvIW,
        SV_1Ag8ZMn4vi2AJcG,
        SV_3EgNt1twOgHuRSu,
        SV_3P0qnj9J5N8sM9o,
        SV_9tLE9UDMgtLp2fk,
        SV_5aTvzleAKM8cBgO,
        SV_6PTobGyKaABt8nI,
        SV_ePOzGHUbhwxMOKa,
        SV_1Y56MXe03Gskhuu,
        SV_0eqCWKU3JRk9zQq,
        SV_6YEAjrF5x93zQV0,
        SV_02ojmiqGl6sRq9E,
        SV_bOOubkgYQkqLsSq,
        SV_1SsPA2Cp1J9kB2S,
        SV_0e6uPBpyYH65zwO,
        SV_ea03SoLLtgNrzAq,
        SV_bBl6bd2MEiacYPs,
        SV_86ZrngSB6hBpqyW,
        SV_aYp8UW8Ey9De6F0,
        SV_1StnsDhZ5oyMIhU,
        SV_dbtC31OqhwpcAL4,
        SV_6PS7A0R03KwXGPY,
        SV_0rAmBRDYlwuJOES,
        SV_5BTt209hwA6mSs6,
        SV_eJzXJjchYy8u3iu,
        SV_7OgqxuLJrhPHIYC,
        SV_eIMumyKDguE2oZg,
        SV_5jNyotNKCdI0ZfM,
        SV_26uq4IUsTtdLJWK,
        SV_3sLXCd1puKRJy2W,
        SV_6nxK3yS5dXCJAXQ,
        SV_bQUoLnGpvUmzBlQ,
        SV_5q0eQNa8IDTaBDw,
        SV_0oIPwBc5YXCzIGy,
        SV_0f94AVpaDvMS9p4,
        SV_0AK390NyfS3e7e6,
        SV_08O6XEAHnYQcBtY,
        SV_cGy95oFZzXvHoQ6,
        SV_6SAeKQyZk2GX6qa,
        SV_9SnRsYQtKKli8lw,
        SV_eL4i5gRPtt5VHca,
        SV_bd78shga9VIE2IC,
        SV_cBbADjvXvJZ0jfo,
        SV_3O8QLB9a2JEGBsq,
        SV_0CbrDZo4MOFqANU

# you can add CloudFormation resource templates here
resources:
  Resources:
    SOMQualtricsSurveyResponseBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.outputBucket}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
