name: Deploy Production Build

on:
  push:
    tags:
      - '*'

concurrency: deploy-production

jobs:
  deploy:
    name: Deploy To AWS
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v5
      with:
        node-version: 20
    - name: install dependencies hoisted for lambda
      run: pnpm install --node-linker=hoisted
    - run: pnpm exec serverless package --stage prod
    - uses: actions/upload-artifact@v4
      with:
        name: prod-som-qualtrics-survey-responses.zip
        path: ./.serverless/som-qualtrics-survey-responses.zip
        if-no-files-found: error
        retention-days: 3
        compression-level: 0
    - run: pnpm exec serverless deploy --stage prod --package ./.serverless --conceal --verbose
    - uses: act10ns/slack@v2
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ILIOS_DEPLOYMENT_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
        message: Qualtrics ETL Production Deploy Failed {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }}
